name: Percy
on: [push, pull_request]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
          auth-token: ${{ secrets.GITHUB_TOKEN }}
          registry-url: https://npm.pkg.github.com
      - name: Percy Test
        uses: percy/storybook-action@v0.1.2
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
